package com.example.ibs.mappers;

import com.example.ibs.controllers.dtos.EquipmentRequestDto;
import com.example.ibs.controllers.dtos.Message;
import com.example.ibs.controllers.dtos.ReportDto;
import com.example.ibs.enteties.applicationforms.EquipmentRequest;
import com.example.ibs.enteties.reportforms.ReportEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.springframework.stereotype.Component;

@Component
@Mapper(componentModel = "spring")
public interface MyMapper {

    ReportDto toDto(ReportEntity reportEntity);

    ReportEntity toEntity(ReportDto reportDto);

    @Mapping(source = "type.name", target = "type")
    EquipmentRequestDto toEquipmentDto(EquipmentRequest equipmentRequest);
    @Mapping(source = "type", target = "type.name")
    EquipmentRequest toEquipment(EquipmentRequestDto equipmentRequestDto);


    @Mapping(source = "id", target = "id")
    //1
    @Mapping(source = "standartPump.yearProduction", target = "field1_1")
    @Mapping(source = "standartPump.countedMounth", target = "field1_2")
    @Mapping(source = "standartPump.uncountedMonth", target = "field1_3")
    @Mapping(source = "standartPump.averageDebit", target = "field1_4")
    @Mapping(source = "standartPump.numberOfWells", target = "field1_5")
    @Mapping(source = "standartPump.extractedFromWells", target = "field1_6")
    @Mapping(source = "electricPump.yearProduction", target = "field2_1")
    @Mapping(source = "electricPump.countedMounth", target = "field2_2")
    @Mapping(source = "electricPump.uncountedMonth", target = "field2_3")
    @Mapping(source = "electricPump.averageDebit", target = "field2_4")
    @Mapping(source = "electricPump.numberOfWells", target = "field2_5")
    @Mapping(source = "electricPump.extractedFromWells", target = "field2_6")
    @Mapping(source = "compressor.yearProduction", target = "field3_1")
    @Mapping(source = "compressor.countedMounth", target = "field3_2")
    @Mapping(source = "compressor.uncountedMonth", target = "field3_3")
    @Mapping(source = "compressor.averageDebit", target = "field3_4")
    @Mapping(source = "compressor.numberOfWells", target = "field3_5")
    @Mapping(source = "compressor.extractedFromWells", target = "field3_6")
    @Mapping(source = "fountainPump.yearProduction", target = "field4_1")
    @Mapping(source = "fountainPump.countedMounth", target = "field4_2")
    @Mapping(source = "fountainPump.uncountedMonth", target = "field4_3")
    @Mapping(source = "fountainPump.averageDebit", target = "field4_4")
    @Mapping(source = "fountainPump.numberOfWells", target = "field4_5")
    @Mapping(source = "fountainPump.extractedFromWells", target = "field4_6")
    @Mapping(source = "otherPump.yearProduction", target = "field5_1")
    @Mapping(source = "otherPump.countedMounth", target = "field5_2")
    @Mapping(source = "otherPump.uncountedMonth", target = "field5_3")
    @Mapping(source = "otherPump.averageDebit", target = "field5_4")
    @Mapping(source = "otherPump.numberOfWells", target = "field5_5")
    @Mapping(source = "otherPump.extractedFromWells", target = "field5_6")
    @Mapping(source = "totalPumpExtracted.yearProduction", target = "field6_1")
    @Mapping(source = "totalPumpExtracted.countedMounth", target = "field6_2")
    @Mapping(source = "totalPumpExtracted.uncountedMonth", target = "field6_3")
    @Mapping(source = "totalPumpExtracted.averageDebit", target = "field6_4")
    @Mapping(source = "totalPumpExtracted.numberOfWells", target = "field6_5")
    @Mapping(source = "totalPumpExtracted.extractedFromWells", target = "field6_6")
    @Mapping(source = "extractedOldWells.yearProduction", target = "field7_1")
    @Mapping(source = "extractedOldWells.countedMounth", target = "field7_2")
    @Mapping(source = "extractedOldWells.uncountedMonth", target = "field7_3")
    @Mapping(source = "extractedOldWells.averageDebit", target = "field7_4")
    @Mapping(source = "extractedOldWells.numberOfWells", target = "field7_5")
    @Mapping(source = "extractedOldWells.extractedFromWells", target = "field7_6")
    @Mapping(source = "extractedLastYearWells.yearProduction", target = "field8_1")
    @Mapping(source = "extractedLastYearWells.countedMounth", target = "field8_2")
    @Mapping(source = "extractedLastYearWells.uncountedMonth", target = "field8_3")
    @Mapping(source = "extractedLastYearWells.averageDebit", target = "field8_4")
    @Mapping(source = "extractedLastYearWells.numberOfWells", target = "field8_5")
    @Mapping(source = "extractedLastYearWells.extractedFromWells", target = "field8_6")
    @Mapping(source = "extractedNewWells.yearProduction", target = "field10_1")
    @Mapping(source = "extractedNewWells.countedMounth", target = "field10_2")
    @Mapping(source = "extractedNewWells.uncountedMonth", target = "field10_3")
    @Mapping(source = "extractedNewWells.averageDebit", target = "field10_4")
    @Mapping(source = "extractedNewWells.numberOfWells", target = "field10_5")
    @Mapping(source = "extractedNewWells.extractedFromWells", target = "field10_6")
    @Mapping(source = "randomOilProduction.yearProduction", target = "field11_1")
    @Mapping(source = "explorationWell.yearProduction", target = "field12_1")
    @Mapping(source = "totalExtractedOil.yearProduction", target = "field13_1")

    //2
    @Mapping(source = "totalWellsBalans.exploatingFund", target = "field41_1")
    @Mapping(source = "totalWellsBalans.operatingFundTotal", target = "field41_2")
    @Mapping(source = "totalWellsBalans.operatingFundExploit", target = "field41_3")
    @Mapping(source = "totalWellsBalans.operatingFundDowntime", target = "field41_4")
    @Mapping(source = "totalWellsBalans.withoutProductionTotal", target = "field41_5")
    @Mapping(source = "totalWellsBalans.withoutProductionLastYear", target = "field41_6")
    @Mapping(source = "totalWellsBalans.awaitingWellsTime", target = "field41_7")
    @Mapping(source = "newWellsBalans.exploatingFund", target = "field42_1")
    @Mapping(source = "newWellsBalans.operatingFundTotal", target = "field42_2")
    @Mapping(source = "newWellsBalans.operatingFundExploit", target = "field42_3")
    @Mapping(source = "newWellsBalans.operatingFundDowntime", target = "field42_4")
    @Mapping(source = "newWellsBalans.withoutProductionTotal", target = "field42_5")
    @Mapping(source = "newWellsBalans.awaitingWellsTime", target = "field42_7")

    //3
    @Mapping(source = "commissioningOilWell.totalCommissioningNewWellValue", target = "field51_1")
    @Mapping(source = "commissioningOilWell.afterDrillingWellValue", target = "field51_2")
    @Mapping(source = "commissioningOilWell.conservationWellValue", target = "field51_3")
    @Mapping(source = "commissioningOilWell.otherWellValue", target = "field51_4")
    @Mapping(source = "commissioningOilWell.lastYearWellValue", target = "field51_5")
    @Mapping(source = "explorianOilWell.totalCommissioningNewWellValue", target = "field52_1")
    @Mapping(source = "commissioningPumpWell.totalCommissioningNewWellValue", target = "field53_1")
    @Mapping(source = "commissioningPumpWell.afterDrillingWellValue", target = "field53_2")
    @Mapping(source = "commissioningPumpWell.conservationWellValue", target = "field53_3")
    @Mapping(source = "commissioningPumpWell.otherWellValue", target = "field53_4")
    @Mapping(source = "commissioningPumpWell.lastYearWellValue", target = "field53_5")
    @Mapping(source = "commissioningElectroPumpWell.totalCommissioningNewWellValue", target = "field54_1")
    @Mapping(source = "commissioningElectroPumpWell.afterDrillingWellValue", target = "field54_2")
    @Mapping(source = "commissioningElectroPumpWell.conservationWellValue", target = "field54_3")
    @Mapping(source = "commissioningElectroPumpWell.otherWellValue", target = "field54_4")
    @Mapping(source = "commissioningElectroPumpWell.lastYearWellValue", target = "field54_5")
    @Mapping(source = "commissioningCompressorWell.totalCommissioningNewWellValue", target = "field55_1")
    @Mapping(source = "commissioningCompressorWell.afterDrillingWellValue", target = "field55_2")
    @Mapping(source = "commissioningCompressorWell.conservationWellValue", target = "field55_3")
    @Mapping(source = "commissioningCompressorWell.otherWellValue", target = "field55_4")
    @Mapping(source = "commissioningCompressorWell.lastYearWellValue", target = "field55_5")
    @Mapping(source = "commissioningFountainPumpWell.totalCommissioningNewWellValue", target = "field56_1")
    @Mapping(source = "commissioningFountainPumpWell.afterDrillingWellValue", target = "field56_2")
    @Mapping(source = "commissioningFountainPumpWell.conservationWellValue", target = "field56_3")
    @Mapping(source = "commissioningFountainPumpWell.otherWellValue", target = "field56_4")
    @Mapping(source = "commissioningFountainPumpWell.lastYearWellValue", target = "field56_5")
    @Mapping(source = "commissioningInjectionPumpWell.totalCommissioningNewWellValue", target = "field57_1")
    @Mapping(source = "commissioningInjectionPumpWell.afterDrillingWellValue", target = "field57_2")
    @Mapping(source = "commissioningInjectionPumpWell.conservationWellValue", target = "field57_3")
    @Mapping(source = "commissioningInjectionPumpWell.otherWellValue", target = "field57_4")
    @Mapping(source = "commissioningInjectionPumpWell.lastYearWellValue", target = "field57_5")
    @Mapping(source = "commissioningInjectionPumpAfterOilWell.totalCommissioningNewWellValue", target = "field58_1")
    //4
    @Mapping(source = "totalImpact.impactFormation", target = "field61_1")
    @Mapping(source = "totalImpact.increaseProduction", target = "field61_2")
    @Mapping(source = "impactWaterInjection.impactFormation", target = "field62_1")
    @Mapping(source = "impactWaterInjection.increaseProduction", target = "field62_2")
    @Mapping(source = "impactHydrodynamicMethods.impactFormation", target = "field63_1")
    @Mapping(source = "impactHydrodynamicMethods.increaseProduction", target = "field63_2")
    @Mapping(source = "impactNewMethods.impactFormation", target = "field64_1")
    @Mapping(source = "impactNewMethods.increaseProduction", target = "field64_2")
    @Mapping(source = "impactNewPhysicoChemicalMethods.impactFormation", target = "field65_1")
    @Mapping(source = "impactNewPhysicoChemicalMethods.increaseProduction", target = "field65_2")
    @Mapping(source = "impactNewThermalMethods.impactFormation", target = "field66_1")
    @Mapping(source = "impactNewThermalMethods.increaseProduction", target = "field66_2")
    //5
    @Mapping(source = "fundReportingPeriod.givingOilAndGas", target = "field111_1")
    @Mapping(source = "fundReportingPeriod.stoppedLastMonth", target = "field112_1")
    @Mapping(source = "fundReportingPeriod.totalOperating", target = "field113_1")
    @Mapping(source = "fundReportingPeriod.notGiveProductLastMonth", target = "field114_1")
    @Mapping(source = "fundReportingPeriod.awaitingAfterDrilling", target = "field115_1")
    @Mapping(source = "fundReportingPeriod.awaitingDrillingNow", target = "field116_1")
    @Mapping(source = "fundReportingPeriod.entireOperationalFund", target = "field117_1")
    @Mapping(source = "fundReportingPeriod.telemechanizedFund", target = "field118_1")
    @Mapping(source = "fundReportingPeriod.givingWaterWell", target = "field119_1")
    @Mapping(source = "fundReportingPeriod.injectionGivingWaterWell", target = "field120_1")
    @Mapping(source = "fundReportingPeriod.currentGivingWaterWell", target = "field121_1")
    @Mapping(source = "fundReportingPeriod.controlGivingWaterWell", target = "field123_1")
    @Mapping(source = "fundReportingPeriod.absorbingWell", target = "field124_1")
    @Mapping(source = "fundReportingPeriod.inConservationWell", target = "field125_1")
    @Mapping(source = "fundReportingPeriod.inAwaitingLiquidationWell", target = "field127_1")
    @Mapping(source = "fundReportingPeriod.liquidatedAfterOperationWell", target = "field128_1")
    @Mapping(source = "fundReportingPeriod.liquidatedAfterDrillingWell", target = "field129_1")
    @Mapping(source = "fundReportingPeriod.totalFundOfWell", target = "field130_1")
    @Mapping(source = "fundReportingPeriod.acceptedWellsFromDrilling", target = "field131_1")
    @Mapping(source = "fundReportingPeriod.acceptedFromGasFund", target = "field132_1")

    @Mapping(source = "fundReportingPeriod.arrivedWell", target = "field141_1")
    @Mapping(source = "fundReportingPeriod.droppedWell", target = "field142_1")
    //6
    @Mapping(source = "productionAssociateGas.factGasProduction", target = "field151_1")
    @Mapping(source = "productionAssociateGas.consumptionGas", target = "field151_2")
    @Mapping(source = "productionAssociateGas.technologicalLosses", target = "field151_3")
    @Mapping(source = "productionAssociateGas.burnedGas", target = "field151_4")
    //7
    @Mapping(source = "oilMovement.remainsBeginning", target = "field161_1")
    @Mapping(source = "oilMovement.extracted", target = "field162_1")
    @Mapping(source = "oilMovement.received", target = "field163_1")
    @Mapping(source = "oilMovement.total", target = "field166_1")
    @Mapping(source = "oilMovement.expenditureOnNeeds", target = "field167_1")
    @Mapping(source = "oilMovement.lossesTotal", target = "field168_1")
    @Mapping(source = "oilMovement.passedTotal", target = "field171_1")
    @Mapping(source = "oilMovement.oilGasFactory", target = "field172_1")
    @Mapping(source = "oilMovement.gasFactory", target = "field173_1")
    @Mapping(source = "oilMovement.handedOil", target = "field174_1")
    @Mapping(source = "oilMovement.export", target = "field175_1")
    @Mapping(source = "oilMovement.drilling", target = "field176_1")
    @Mapping(source = "oilMovement.otherMineFactory", target = "field177_1")
    @Mapping(source = "oilMovement.otherFactory", target = "field178_1")
    @Mapping(source = "oilMovement.totalExpense", target = "field179_1")
    @Mapping(source = "oilMovement.remainsEnd", target = "field180_1")
    @Mapping(source = "oilMovement.remainsEndOilPipelinesAndTanks", target = "field181_1")

    //8
    @Mapping(source = "oilPreparation.liquidIntake", target = "field182_1")
    @Mapping(source = "oilPreparation.receivedOil", target = "field183_1")
    @Mapping(source = "oilPreparation.preparedOil", target = "field184_1")
    @Mapping(source = "oilPreparation.oilLosses", target = "field185_1")
    Message toMessage(ReportDto dto);

    @Mapping(target = "standartPump.yearProduction", source = "field1_1")
    @Mapping(target = "standartPump.countedMounth", source = "field1_2")
    @Mapping(target = "standartPump.uncountedMonth", source = "field1_3")
    @Mapping(target = "standartPump.averageDebit", source = "field1_4")
    @Mapping(target = "standartPump.numberOfWells", source = "field1_5")
    @Mapping(target = "standartPump.extractedFromWells", source = "field1_6")
    @Mapping(target = "electricPump.yearProduction", source = "field2_1")
    @Mapping(target = "electricPump.countedMounth", source = "field2_2")
    @Mapping(target = "electricPump.uncountedMonth", source = "field2_3")
    @Mapping(target = "electricPump.averageDebit", source = "field2_4")
    @Mapping(target = "electricPump.numberOfWells", source = "field2_5")
    @Mapping(target = "electricPump.extractedFromWells", source = "field2_6")
    @Mapping(target = "compressor.yearProduction", source = "field3_1")
    @Mapping(target = "compressor.countedMounth", source = "field3_2")
    @Mapping(target = "compressor.uncountedMonth", source = "field3_3")
    @Mapping(target = "compressor.averageDebit", source = "field3_4")
    @Mapping(target = "compressor.numberOfWells", source = "field3_5")
    @Mapping(target = "compressor.extractedFromWells", source = "field3_6")
    @Mapping(target = "fountainPump.yearProduction", source = "field4_1")
    @Mapping(target = "fountainPump.countedMounth", source = "field4_2")
    @Mapping(target = "fountainPump.uncountedMonth", source = "field4_3")
    @Mapping(target = "fountainPump.averageDebit", source = "field4_4")
    @Mapping(target = "fountainPump.numberOfWells", source = "field4_5")
    @Mapping(target = "fountainPump.extractedFromWells", source = "field4_6")
    @Mapping(target = "otherPump.yearProduction", source = "field5_1")
    @Mapping(target = "otherPump.countedMounth", source = "field5_2")
    @Mapping(target = "otherPump.uncountedMonth", source = "field5_3")
    @Mapping(target = "otherPump.averageDebit", source = "field5_4")
    @Mapping(target = "otherPump.numberOfWells", source = "field5_5")
    @Mapping(target = "otherPump.extractedFromWells", source = "field5_6")
    @Mapping(target = "totalPumpExtracted.yearProduction", source = "field6_1")
    @Mapping(target = "totalPumpExtracted.countedMounth", source = "field6_2")
    @Mapping(target = "totalPumpExtracted.uncountedMonth", source = "field6_3")
    @Mapping(target = "totalPumpExtracted.averageDebit", source = "field6_4")
    @Mapping(target = "totalPumpExtracted.numberOfWells", source = "field6_5")
    @Mapping(target = "totalPumpExtracted.extractedFromWells", source = "field6_6")
    @Mapping(target = "extractedOldWells.yearProduction", source = "field7_1")
    @Mapping(target = "extractedOldWells.countedMounth", source = "field7_2")
    @Mapping(target = "extractedOldWells.uncountedMonth", source = "field7_3")
    @Mapping(target = "extractedOldWells.averageDebit", source = "field7_4")
    @Mapping(target = "extractedOldWells.numberOfWells", source = "field7_5")
    @Mapping(target = "extractedOldWells.extractedFromWells", source = "field7_6")
    @Mapping(target = "extractedLastYearWells.yearProduction", source = "field8_1")
    @Mapping(target = "extractedLastYearWells.countedMounth", source = "field8_2")
    @Mapping(target = "extractedLastYearWells.uncountedMonth", source = "field8_3")
    @Mapping(target = "extractedLastYearWells.averageDebit", source = "field8_4")
    @Mapping(target = "extractedLastYearWells.numberOfWells", source = "field8_5")
    @Mapping(target = "extractedLastYearWells.extractedFromWells", source = "field8_6")
    @Mapping(target = "extractedNewWells.yearProduction", source = "field10_1")
    @Mapping(target = "extractedNewWells.countedMounth", source = "field10_2")
    @Mapping(target = "extractedNewWells.uncountedMonth", source = "field10_3")
    @Mapping(target = "extractedNewWells.averageDebit", source = "field10_4")
    @Mapping(target = "extractedNewWells.numberOfWells", source = "field10_5")
    @Mapping(target = "extractedNewWells.extractedFromWells", source = "field10_6")
    @Mapping(target = "randomOilProduction.yearProduction", source = "field11_1")
    @Mapping(target = "explorationWell.yearProduction", source = "field12_1")
    @Mapping(target = "totalExtractedOil.yearProduction", source = "field13_1")
    @Mapping(target = "totalWellsBalans.exploatingFund", source = "field41_1")
    @Mapping(target = "totalWellsBalans.operatingFundTotal", source = "field41_2")
    @Mapping(target = "totalWellsBalans.operatingFundExploit", source = "field41_3")
    @Mapping(target = "totalWellsBalans.operatingFundDowntime", source = "field41_4")
    @Mapping(target = "totalWellsBalans.withoutProductionTotal", source = "field41_5")
    @Mapping(target = "totalWellsBalans.withoutProductionLastYear", source = "field41_6")
    @Mapping(target = "totalWellsBalans.awaitingWellsTime", source = "field41_7")
    @Mapping(target = "newWellsBalans.exploatingFund", source = "field42_1")
    @Mapping(target = "newWellsBalans.operatingFundTotal", source = "field42_2")
    @Mapping(target = "newWellsBalans.operatingFundExploit", source = "field42_3")
    @Mapping(target = "newWellsBalans.operatingFundDowntime", source = "field42_4")
    @Mapping(target = "newWellsBalans.withoutProductionTotal", source = "field42_5")
    @Mapping(target = "newWellsBalans.awaitingWellsTime", source = "field42_7")
    @Mapping(target = "commissioningOilWell.totalCommissioningNewWellValue", source = "field51_1")
    @Mapping(target = "commissioningOilWell.afterDrillingWellValue", source = "field51_2")
    @Mapping(target = "commissioningOilWell.conservationWellValue", source = "field51_3")
    @Mapping(target = "commissioningOilWell.otherWellValue", source = "field51_4")
    @Mapping(target = "commissioningOilWell.lastYearWellValue", source = "field51_5")
    @Mapping(target = "explorianOilWell.totalCommissioningNewWellValue", source = "field52_1")
    @Mapping(target = "commissioningPumpWell.totalCommissioningNewWellValue", source = "field53_1")
    @Mapping(target = "commissioningPumpWell.afterDrillingWellValue", source = "field53_2")
    @Mapping(target = "commissioningPumpWell.conservationWellValue", source = "field53_3")
    @Mapping(target = "commissioningPumpWell.otherWellValue", source = "field53_4")
    @Mapping(target = "commissioningPumpWell.lastYearWellValue", source = "field53_5")
    @Mapping(target = "commissioningElectroPumpWell.totalCommissioningNewWellValue", source = "field54_1")
    @Mapping(target = "commissioningElectroPumpWell.afterDrillingWellValue", source = "field54_2")
    @Mapping(target = "commissioningElectroPumpWell.conservationWellValue", source = "field54_3")
    @Mapping(target = "commissioningElectroPumpWell.otherWellValue", source = "field54_4")
    @Mapping(target = "commissioningElectroPumpWell.lastYearWellValue", source = "field54_5")
    @Mapping(target = "commissioningCompressorWell.totalCommissioningNewWellValue", source = "field55_1")
    @Mapping(target = "commissioningCompressorWell.afterDrillingWellValue", source = "field55_2")
    @Mapping(target = "commissioningCompressorWell.conservationWellValue", source = "field55_3")
    @Mapping(target = "commissioningCompressorWell.otherWellValue", source = "field55_4")
    @Mapping(target = "commissioningCompressorWell.lastYearWellValue", source = "field55_5")
    @Mapping(target = "commissioningFountainPumpWell.totalCommissioningNewWellValue", source = "field56_1")
    @Mapping(target = "commissioningFountainPumpWell.afterDrillingWellValue", source = "field56_2")
    @Mapping(target = "commissioningFountainPumpWell.conservationWellValue", source = "field56_3")
    @Mapping(target = "commissioningFountainPumpWell.otherWellValue", source = "field56_4")
    @Mapping(target = "commissioningFountainPumpWell.lastYearWellValue", source = "field56_5")
    @Mapping(target = "commissioningInjectionPumpWell.totalCommissioningNewWellValue", source = "field57_1")
    @Mapping(target = "commissioningInjectionPumpWell.afterDrillingWellValue", source = "field57_2")
    @Mapping(target = "commissioningInjectionPumpWell.conservationWellValue", source = "field57_3")
    @Mapping(target = "commissioningInjectionPumpWell.otherWellValue", source = "field57_4")
    @Mapping(target = "commissioningInjectionPumpWell.lastYearWellValue", source = "field57_5")
    @Mapping(target = "commissioningInjectionPumpAfterOilWell.totalCommissioningNewWellValue", source = "field58_1")
    @Mapping(target = "totalImpact.impactFormation", source = "field61_1")
    @Mapping(target = "totalImpact.increaseProduction", source = "field61_2")
    @Mapping(target = "impactWaterInjection.impactFormation", source = "field62_1")
    @Mapping(target = "impactWaterInjection.increaseProduction", source = "field62_2")
    @Mapping(target = "impactHydrodynamicMethods.impactFormation", source = "field63_1")
    @Mapping(target = "impactHydrodynamicMethods.increaseProduction", source = "field63_2")
    @Mapping(target = "impactNewMethods.impactFormation", source = "field64_1")
    @Mapping(target = "impactNewMethods.increaseProduction", source = "field64_2")
    @Mapping(target = "impactNewPhysicoChemicalMethods.impactFormation", source = "field65_1")
    @Mapping(target = "impactNewPhysicoChemicalMethods.increaseProduction", source = "field65_2")
    @Mapping(target = "impactNewThermalMethods.impactFormation", source = "field66_1")
    @Mapping(target = "impactNewThermalMethods.increaseProduction", source = "field66_2")
    @Mapping(target = "fundReportingPeriod.givingOilAndGas", source = "field111_1")
    @Mapping(target = "fundReportingPeriod.stoppedLastMonth", source = "field112_1")
    @Mapping(target = "fundReportingPeriod.totalOperating", source = "field113_1")
    @Mapping(target = "fundReportingPeriod.notGiveProductLastMonth", source = "field114_1")
    @Mapping(target = "fundReportingPeriod.awaitingAfterDrilling", source = "field115_1")
    @Mapping(target = "fundReportingPeriod.awaitingDrillingNow", source = "field116_1")
    @Mapping(target = "fundReportingPeriod.entireOperationalFund", source = "field117_1")
    @Mapping(target = "fundReportingPeriod.telemechanizedFund", source = "field118_1")
    @Mapping(target = "fundReportingPeriod.givingWaterWell", source = "field119_1")
    @Mapping(target = "fundReportingPeriod.injectionGivingWaterWell", source = "field120_1")
    @Mapping(target = "fundReportingPeriod.currentGivingWaterWell", source = "field121_1")
    @Mapping(target = "fundReportingPeriod.controlGivingWaterWell", source = "field123_1")
    @Mapping(target = "fundReportingPeriod.absorbingWell", source = "field124_1")
    @Mapping(target = "fundReportingPeriod.inConservationWell", source = "field125_1")
    @Mapping(target = "fundReportingPeriod.inAwaitingLiquidationWell", source = "field127_1")
    @Mapping(target = "fundReportingPeriod.liquidatedAfterOperationWell", source = "field128_1")
    @Mapping(target = "fundReportingPeriod.liquidatedAfterDrillingWell", source = "field129_1")
    @Mapping(target = "fundReportingPeriod.totalFundOfWell", source = "field130_1")
    @Mapping(target = "fundReportingPeriod.acceptedWellsFromDrilling", source = "field131_1")
    @Mapping(target = "fundReportingPeriod.acceptedFromGasFund", source = "field132_1")
    @Mapping(target = "fundReportingPeriod.arrivedWell", source = "field141_1")
    @Mapping(target = "fundReportingPeriod.droppedWell", source = "field142_1")
    @Mapping(target = "productionAssociateGas.factGasProduction", source = "field151_1")
    @Mapping(target = "productionAssociateGas.consumptionGas", source = "field151_2")
    @Mapping(target = "productionAssociateGas.technologicalLosses", source = "field151_3")
    @Mapping(target = "productionAssociateGas.burnedGas", source = "field151_4")
    @Mapping(target = "oilMovement.remainsBeginning", source = "field161_1")
    @Mapping(target = "oilMovement.extracted", source = "field162_1")
    @Mapping(target = "oilMovement.received", source = "field163_1")
    @Mapping(target = "oilMovement.total", source = "field166_1")
    @Mapping(target = "oilMovement.expenditureOnNeeds", source = "field167_1")
    @Mapping(target = "oilMovement.lossesTotal", source = "field168_1")
    @Mapping(target = "oilMovement.passedTotal", source = "field171_1")
    @Mapping(target = "oilMovement.oilGasFactory", source = "field172_1")
    @Mapping(target = "oilMovement.gasFactory", source = "field173_1")
    @Mapping(target = "oilMovement.handedOil", source = "field174_1")
    @Mapping(target = "oilMovement.export", source = "field175_1")
    @Mapping(target = "oilMovement.drilling", source = "field176_1")
    @Mapping(target = "oilMovement.otherMineFactory", source = "field177_1")
    @Mapping(target = "oilMovement.otherFactory", source = "field178_1")
    @Mapping(target = "oilMovement.totalExpense", source = "field179_1")
    @Mapping(target = "oilMovement.remainsEnd", source = "field180_1")
    @Mapping(target = "oilMovement.remainsEndOilPipelinesAndTanks", source = "field181_1")
    @Mapping(target = "oilPreparation.liquidIntake", source = "field182_1")
    @Mapping(target = "oilPreparation.receivedOil", source = "field183_1")
    @Mapping(target = "oilPreparation.preparedOil", source = "field184_1")
    @Mapping(target = "oilPreparation.oilLosses", source = "field185_1")
    ReportDto inMessageToDto(Message message);
}
